### ISSUE TITLE
Cambios en el formulario de borrador

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Uni-n-Provincial-de-Cooperativas#2]
https://drive.google.com/a/cidmultimedia.es/file/d/0B2FQ85n9y_g7cG1PTS1Eb3lUWFhjU0l5VTJ2Y3FpM3d6OFdN/view?usp=sharing

http://www.evernote.com/l/AA8pxrM0qd1LVqVWtuebTciWjma7vcXzcJ8/

**Comment by anacid** [comment]
Estos cambios no están ya realizados???

**Comment by gregorioruiz** [comment]
Pero no está puesto en su programa actual, porque todo el paquete de cambios de borrador lo había dejado para el año que viene. 
Tienes razón que igual habría que ponerle esto ya para lo que queda de ejercicio.
