### ISSUE TITLE
Depósito de cuentas

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Uni-n-Provincial-de-Cooperativas#3]
https://drive.google.com/a/cidmultimedia.es/file/d/0B2FQ85n9y_g7QVp5VnZVNTRHeGF0Y3E1aTZQN2IxYVFNQkxr/view?usp=sharing

**Comment by anacid** [comment]
Paso la imagen con el detalle de las modificaciones a hacer:

![Image.png](https://zube.io/files/anacid/0049e7503b43701d9630ee70840272c4.png)

**Comment by anacid** [comment]
Patrimonio neto y pasivo, hay varios cambios a realizar, pero si no lo entiendes lo vemos, está un poco lioso
![Image.png](https://zube.io/files/anacid/58a00feb275eb872f02572a27e013629.png)

**Comment by anacid** [comment]
En la cuenta de pérdidas y ganancias tenemos que repasar los signos " - ", para ponerlos como lo suyo, nosotros lo tenemos al revés, los que él pone con signo negativo, nosotros los tenemos con signo positivo, y al revés.

**Comment by anacid** [comment]
Teniendo generado el patrimonio neto y pasivo, podemos generar el impreso que nos ha pasado de cambios en el patrimonio neto, ya lo vemos, y tu decides

**Comment by anacid** [comment]
Tenemos que repasar la condición puesta en la línea 51, porque no suma la cuenta 47. Quizás sea mejor que lo veamos sobre la marcha.
