### ISSUE TITLE
Resúmenes de IVA

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Uni-n-Provincial-de-Cooperativas#4]
http://www.evernote.com/l/AA9aRqsOXSNH-bHeUsNxCcbzXKuR9_sJOxs/

http://www.evernote.com/l/AA9FC-PXKOdDkZaysiLsGSYmWbETXcFlQkQ/

**Comment by anacid** [comment]
UNION COOPERATIVAS	
	
DATOS IVA	
	
Posibles combinaciones con los distintos tipos de factura	
	
TIPO DE FACTURA RECIBIDA	          CLAVE DE OPERACIÓN
Normal	                                               Operación habitual
Normal	                                               Bienes de inversión
Normal                                                    Inversión del sujeto pasivo
	
Intracumunitaria	                               Adquisic. Intracomunitarias (Eliminar??)
Intracumunitaria	                               Bienes de inversión
Intracumunitaria	                               Inversión del sujeto pasivo
	
Bienes de inversión ???

**Comment by anacid** [comment]
Si te parece se lo envío a Carlos para que el me diga, si caben más posibilidades, que imagino que sí.

**Comment by gregorioruiz** [comment]
Hoja excel de lo hablado con Carlos

https://drive.google.com/open?id=0B2FQ85n9y_g7NFdEU1BNQjZBYms
